# Generated by Django 5.1.6 on 2025-03-08 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='书名')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='出版日期')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'books',
            },
        ),
    ]
