name: "初入Django"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 运行
        required: true
        default: true
        type: boolean

jobs:
    build:
        runs-on: windows-latest
        steps:
          - name: 读取仓库代码
            uses: actions/checkout@v4
          - name: 安装依赖
            uses: eifinger/setup-rye@v4
            with:
              version: 'latest'
          - name: 运行Django
            run: |
              rye init
              rye sync
              cd quick_start_01
          - name: 上传文件
            uses: actions/upload-artifact@v4
            with:
              name: build
              path: quick_start_01/dist/manage.exe

