name: "结合前端的打包"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 运行
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 读取仓库代码
        uses: actions/checkout@v4

      - name: 安装rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
          version: 'latest'

      - name: 安装依赖
        run: rye sync

      - name: 打包
        run: |
          cd src/show_data_02
          rye run build_add_data

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: src/show_data_02/dist/manage.exe
