name: 打包
on:
  workflow_dispatch:
    inputs:
      name:
        description: "运行项目的序号"
        required: true
        default: "01"
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 读取仓库代码
        uses: actions/checkout@v4

      - name: 安装rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
          version: 'latest'

      - name: 安装依赖
        run: rye sync

      - name: 动态选择目录并进入
        id: select_dir
        run: |
          # 获取输入的序号
          $seq_number = "${{ github.event.inputs.name }}"
          # 查找符合条件的目录
          $dirs = Get-ChildItem -Directory -Path src | Where-Object { $_.Name -match '_\d+$' } | Select-Object -ExpandProperty FullName
          Write-Host "Found directories: $dirs"
          # 选择对应的目录（假设目录名称以序号结尾）
          $target_dir = $dirs | Where-Object { $_ -match "_$seq_number$" } | Select-Object -First 1
          if ($target_dir) {
            Write-Host "Target directory: $target_dir"
            echo "target_dir=$target_dir" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "No directory found for sequence number $seq_number. Exiting."
            exit 1
          }

      - name: 打包
        run: |
          # 读取上一步选择的目录
          $target_dir = "${{ steps.select_dir.outputs.target_dir }}"
          # 进入目标目录
          cd $target_dir
          pwd
          # 执行打包命令
          rye run build_add_data

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ steps.select_dir.outputs.target_dir }}/dist/manage.exe