name: 缓存rye
on:
  workflow_dispatch:
    inputs:
        name:
            description: 运行
            required: true
            default: true
            type: boolean

jobs:
    build:
        runs-on: windows-latest
        steps:
        - name: 读取仓库代码
          uses: actions/checkout@v4

        - name: 安装rye
          uses: eifinger/setup-rye@v4
          with:
            enable-cache: true
            version: 'latest'


